// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides workout suggestions based on user fitness goals and workout history.
 *
 * - workoutSuggestion - A function that generates workout suggestions.
 * - WorkoutSuggestionInput - The input type for the workoutSuggestion function.
 * - WorkoutSuggestionOutput - The return type for the workoutSuggestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const WorkoutSuggestionInputSchema = z.object({
  fitnessGoals: z
    .string()
    .describe('The fitness goals of the user (e.g., weight loss, muscle gain, endurance).'),
  pastWorkoutHistory: z
    .string()
    .describe('A description of the user\'s past workout history, including types of exercises, frequency, and duration.'),
  availableEquipment: z
    .string()
    .optional()
    .describe('The equipment the user has access to (e.g., dumbbells, resistance bands, gym).'),
  experienceLevel: z
    .enum(['beginner', 'intermediate', 'advanced'])
    .describe('The experience level of the user.'),
});

export type WorkoutSuggestionInput = z.infer<typeof WorkoutSuggestionInputSchema>;

const WorkoutSuggestionOutputSchema = z.object({
  workoutSuggestion: z.string().describe('A workout suggestion based on the user input.'),
  reasoning: z.string().describe('The reasoning behind the workout suggestion.'),
});

export type WorkoutSuggestionOutput = z.infer<typeof WorkoutSuggestionOutputSchema>;

export async function workoutSuggestion(input: WorkoutSuggestionInput): Promise<WorkoutSuggestionOutput> {
  return workoutSuggestionFlow(input);
}

const workoutSuggestionPrompt = ai.definePrompt({
  name: 'workoutSuggestionPrompt',
  input: {schema: WorkoutSuggestionInputSchema},
  output: {schema: WorkoutSuggestionOutputSchema},
  prompt: `You are a personal trainer who gives workout suggestions based on the user's fitness goals, workout history, available equipment and experience level.

Fitness Goals: {{{fitnessGoals}}}
Past Workout History: {{{pastWorkoutHistory}}}
Available Equipment: {{{availableEquipment}}}
Experience Level: {{{experienceLevel}}}

Suggest a workout routine that aligns with their goals and experience level. Provide a brief explanation of why you are suggesting this workout routine.
`,
});

const workoutSuggestionFlow = ai.defineFlow(
  {
    name: 'workoutSuggestionFlow',
    inputSchema: WorkoutSuggestionInputSchema,
    outputSchema: WorkoutSuggestionOutputSchema,
  },
  async input => {
    const {output} = await workoutSuggestionPrompt(input);
    return output!;
  }
);
